version: '2'
services:
    zookeeper:
      image: kscape/docker-zookeeper:latest
      ports:
        - "2181:2181"

    kafka:
      image: kscape/docker-kafka:latest
      ports:
        - "9092:9092"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: "192.168.0.33"
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_OFFSETS_STORAGE: kafka
        KAFKA_CREATE_TOPICS: "test-topic:1"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      depends_on:
        - zookeeper
